### ISSUE TITLE
podcast issue/ php issues

### ISSUE THREAD

**Issue by glgprasad** [Joomla-Bible-Study/Proclaim#827]
![podcast error](https://user-images.githubusercontent.com/79415321/108632632-f4be6680-7495-11eb-8fee-875fd86d503b.jpg)
![WhatsApp Image 2021-02-18 at 4 10 58 PM](https://user-images.githubusercontent.com/79415321/108632659-1fa8ba80-7496-11eb-879a-7ad4ab651d61.jpeg)
![WhatsApp Image 2021-02-18 at 3 58 35 PM](https://user-images.githubusercontent.com/79415321/108632664-20d9e780-7496-11eb-9376-97c3e140fea9.jpeg)

**Comment by bcordis** [comment]
Sent test file to client to see if it fixes problem.

**Comment by glgprasad** [comment]
![2021-02-22 08_52_43-Window](https://user-images.githubusercontent.com/79415321/108653002-6ecd0a80-74eb-11eb-86fa-5f6f57216582.png)

**Comment by glgprasad** [comment]
same error repeated. regards

**Comment by glgprasad** [comment]
![error](https://user-images.githubusercontent.com/79415321/108663972-ca04fa00-74f7-11eb-9cf6-339a02d0081b.jpg)

**Comment by glgprasad** [comment]
same error repeated sir

**Comment by bcordis** [comment]
Got admin credentials and doing additional testing.￼

**Comment by bcordis** [comment]
Fix tested on the site and working.
