### ISSUE TITLE
Image changer needs form checker

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#832]
You can change something to Image, and choose an Icon instead of an image below - which breaks and only text shows. Should check the form to make sure it matches. Admin Image changer.

**Comment by bcordis** [comment]
@tomfuller2 Can you help me with this one more. How do I reproduce the bug?

**Comment by tomfuller2** [comment]
I can work on that.

**Comment by bcordis** [comment]
Ok thanks as I could not fallow the bug flow to reproduce it.

**Comment by bcordis** [comment]
Delayed to work on image checker later after 9.2.7

**Comment by tomfuller2** [comment]
I removed this functionality. https://github.com/Joomla-Bible-Study/Proclaim/commit/39ddad4d226a8287c67a5d74a6b173711c987d88
