### ISSUE TITLE
Sermons View Page builder section over usage

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Proclaim#838]
Looking at the code and following how it's being used. Right now it looks like we are calling it but we don't need it all the time.

Need to look at seeing if we could narrow the usage down.

site\views\sermon\view.html.php line 288

**Comment by tomfuller2** [comment]
Looks like only call it once in sermon/view.html.php and that is only if the user has turned on expert mode. Do we still use expert mode?

**Comment by bcordis** [comment]
I'm not sure we use it any more and the way it's coded right now it runs the through the code every time. Lot of over work as it's not used.

**Comment by bcordis** [comment]
Man, we are running into the same problem within the model presenting the same over usage of the processes. Looks like we need to optimize them both.

**Comment by bcordis** [comment]
@tomfuller2 I think this would be a fix for us now.
