### ISSUE TITLE
Delete media not working at this time. Not sure if it ever was.

### ISSUE THREAD

**Issue by bcordis** [Joomla-Bible-Study/Proclaim#855]
Would need to look into

**Comment by st-anton** [comment]
Hi Brent, I was absent for a long time...
I debugged is and found that the admin model/mediafile.php line 713 is called, where state is checked for -2 (line 717). But `state` is not part of the table variable. It is simply not there. So the call fails.
Deleting a study, there is no function `canDelete` in the studies model. So studies can be deleted.

**Comment by bcordis** [comment]
@st-anton so glad you have been able to take time to look at the system. I'll try and make a pull request with this change and see if you can look at it also.
