### ISSUE TITLE
error when clicking on the sermon title

### ISSUE THREAD

**Issue by glgprasad** [Joomla-Bible-Study/Proclaim#858]
![2021_04_30_13_24_36_Window](https://user-images.githubusercontent.com/79415321/116665975-0c472d80-a9b8-11eb-9869-53e39aeeafc9.jpg)
![WhatsApp Image 2021-04-30 at 1 23 25 PM](https://user-images.githubusercontent.com/79415321/116666558-b757e700-a9b8-11eb-8e4d-a247d55a11f4.jpeg)

I am not having issue with the playing the media. but when clicking on the sermon title it is going to the error page.

http://tbolf.org/newsite
(The Bread of Life Fellowship, Oman)

**Comment by bcordis** [comment]
found online Proclaim/site/helpers/relatedstudies.php:26 looking into it.

**Comment by bcordis** [comment]
This is a bug with 7.3.x version of PHP.  seeing if we need to fix this or force them to upgrade to PHP 7.4 or grater.
