### ISSUE TITLE
When creating menu item to Proclaim, application dies

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#878]
Create a study list menu item.

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>

<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<meta name="CocoaVersion" content="2113">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 13.0px 'Helvetica Neue'}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
table.t1 {border-collapse: collapse}
td.td1 {border-style: solid; border-width: 1.0px 1.0px 1.0px 1.0px; border-color: #9a9a9a #9a9a9a #9a9a9a #9a9a9a; padding: 1.0px 5.0px 1.0px 5.0px}
</style>
</head>
<body>
<p class="p1">If difficulties persist, please contact the website administrator and report the error below.</p>
<p class="p1"><b>0</b>&#xA0;Class 'CWM\Component\Proclaim\Administrator\Extension\ProclaimComponent' not found</p>

Call stack |   |  
-- | -- | --
# | Function | Location
1 | () | /Users/Tom/PhpstormProjects/Proclaim/admin/services/provider.php:49
2 | class@anonymous/Users/Tom/PhpstormProjects/Proclaim/admin/services/provider.php:30$11c7->{closure}() | JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:182

</body>
</html>

**Comment by bcordis** [comment]
I have tested this on my system and can not reproduce it after doing the updates. Please pull from j4bata to get the latest fixes.

**Comment by tomfuller2** [comment]
I still have the problem after updating from j4bata and to Joomla 4.05.
No errors without any Proclaim menus. If I create a studieslist menu item then I get this
Error:

Class 'CWM\Component\Proclaim\Administrator\Extension\ProclaimComponent' not found
Call stack
#          Function          Location
1          ()          /Users/Tom/PhpstormProjects/Proclaim/admin/services/provider.php:49
2          class@anonymous/Users/Tom/PhpstormProjects/Proclaim/admin/services/provider.php:30$516->{closure}()            JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:182

Provider.php 49 reads: 
$component = new ProclaimComponent($container->get(ComponentDispatcherFactoryInterface::class));

**Comment by bcordis** [comment]
Forgot to push the new code. Try it now.

**Comment by tomfuller2** [comment]
Same issue. When I unpublish the menu item, the site works fine.

**Comment by tomfuller2** [comment]
I added those lines to the autoload file under libraries | vendor. Didn't work. There are two other files of the same name. Should I add it there too?

**Comment by bcordis** [comment]
There should be only one autoload_psr4.php under administrator\cache folder. I don't think it's located any where else.

**Comment by tomfuller2** [comment]
There are actually 3. I edited the cache one - the correct syntax needs to be:

'CWM\\Component\\Proclaim\\Administrator\\' => [JPATH_ADMINISTRATOR . '/components/com_proclaim/src'], 'CWM\\Component\\Proclaim\\Site\\' => [JPATH_SITE . '/components/com_proclaim/src'],

Notice the double back slashes in the namespace, and, most important, the trailing double slash. Now I'm back up to working!
