### ISSUE TITLE
Podcast XML not getting updated

### ISSUE THREAD

**Issue by glgprasad** [Joomla-Bible-Study/Proclaim#879]
Dear team, 

https://tbolf.org/newsite/tbolf.xml is not getting updated inspite of the media files having the selected podcast.

site: http://tbolf.org/newsite

regards

**Comment by tomfuller2** [comment]
I see a message from January 2nd in the XML file. Has the problem been
resolved on your end?

**Comment by glgprasad** [comment]
Dear Sir,

it is been sorted out with the help of Bro.Brent Cordis.

Thank you very much sir,

God Bless you and your ministry.

Prasad
