### ISSUE TITLE
$model->getIdToNameReverseLookup(); not working in field

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#882]
Admin/Field/serverField

When refactoring the $model->getIdToNameReverseLookup(); function not available. I don't know the equivalent

**Comment by bcordis** [comment]
@tomfuller2 Can you point me to the original file this was located in?

**Comment by tomfuller2** [comment]
Admin / src / Field / ServerField

**Comment by tomfuller2** [comment]
Fixed. I moved the function to the serverField.php.
