### ISSUE TITLE
Using download popup message results in popup icon dissapearing

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#883]
to reproduce: choose Show popup message before download in the template. 

On studylist the popup icon disappears.

**Comment by bcordis** [comment]
@tomfuller2 try testing with the new fix.

**Comment by tomfuller2** [comment]
It opens in a new tab, not a modal. Also, there is a MySQL error when you try to click on the download.

**Comment by bcordis** [comment]
@tomfuller2 This may be something we need to re-design as it was a pop up and not a model. Can you send me SQL error?

**Comment by tomfuller2** [comment]
This was fixed with: https://github.com/Joomla-Bible-Study/Proclaim/commit/30c03371e39dba41ce84e2ccba38d6edc2c897f8
