### ISSUE TITLE
Save and Cancel buttons don't work on commentform site side

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#889]
Try to edit a comment - you cannot save or cancel

**Comment by bcordis** [comment]
I'll look into the problem as looks to be a JavaScript problem.

**Comment by bcordis** [comment]
Considering not using this on the front side due to complications and not being needed as people have rights to the back end just fine.

**Comment by tomfuller2** [comment]
Right. We will want to allow comments to add to a study, but we don't need to admin them from the site side.

**Comment by tomfuller2** [comment]
We removed this functionality
