### ISSUE TITLE
Omit download of external code whenever possible; add info in release

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Proclaim#905]
At least in Europe currently a lot of warnings (with costs of several 100 Euros / $) are sent to webpages, where external code is used. They claim a violation of GDPR if external code is used, the external link server may collect data of the users.
I found external code of the frontpage:
- [https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js](https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js) but a similar (but maybe outdated) file is already in media/com_biblestudy/fancybox (version 3.1.20?)
- [https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css](https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css) but a similar (but maybe outdated) file is already in media/com_biblestudy/fancybox
- [https://use.fontawesome.com/releases/v5.12.0/js/all.js](https://use.fontawesome.com/releases/v5.12.0/js/all.js) and [https://use.fontawesome.com/releases/v5.12.0/js/v4-shims.js](https://use.fontawesome.com/releases/v5.12.0/js/v4-shims.js) but I did not find a possibility to switch off the use of fontawesome (admin/helpers/html/proclaim.php)
- As far as I see, also the JWPlayer gets code from [https://ssl.p.jwpcdn.com/](https://ssl.p.jwpcdn.com/)

In general: It is helpfull for the webmaster to have as much as possible code locally in the installation, if possible and allowed to distribute the code. If it is not possible or allowed, there should be a hint for the webmaster for his disclaimer in the release information.

**Comment by st-anton** [comment]
For the player it is helpful to offer native html5 <audio> and <video> as an alternative to pwplayer (and or other players.

**Comment by bcordis** [comment]
We need to determine what all has alternatives for JWPlayer. We will need to make a new parameter for them to switch in admin for GDPR to disable the off-site loading of scripts. It looks like the JWPlayer code is no longer offered for local use.

**Comment by bcordis** [comment]
I'll need to work on the html5 workup to fix this problem. All the systems are using the JWPlayer and need a quick move to non-JWPlayers within the migration.

**Comment by bcordis** [comment]
We have now removed all CDN references from the outside code. Joomla now offers FontAwsome natively, and the other code is loading locally. We will look into further optimization for GDPR needs.
