### ISSUE TITLE
Pagination on some admin lists does not work

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#906]
Clicking one of the links on the admin side does not move forward in the list

**Comment by tomfuller2** [comment]
THis is on the mediafiles view

**Comment by tomfuller2** [comment]
What's happening is $limitstart is not being passed to the pagination method.

**Comment by tomfuller2** [comment]
This is happening on all admin views.

**Comment by tomfuller2** [comment]
Fixed - duplicate pagination found. Removed one. https://github.com/Joomla-Bible-Study/Proclaim/commit/c4ed3db242c3d08fdc3115b0acaa997e75ecd3e0

**Comment by tomfuller2** [comment]
Fixed this in messages list but it still doesn't work in media files.

**Comment by tomfuller2** [comment]
Teachers list also does not work with pagination.

**Comment by tomfuller2** [comment]
Also series.

Topics works. Servers works. Comments work. Templatecodes work.

**Comment by tomfuller2** [comment]
So just to update:

Pagination does NOT work on admin: MediaFiles, Teachers, Series. 

The links at the bottom of the page are correct - the same for the working Studies list.

<a aria-label="Go to page 3" href="#" onclick="document.adminForm.limitstart.value=40; Joomla.submitform();return false;" class="page-link">
            3        </a>

But $limitstart is being removed prior to it getting to the Pagination.php file under Libraries/src/Pagination

**Comment by tomfuller2** [comment]
I'm wondering if there is a way to test the javascript here. Seems the info for the limitstart is correct in a < a href but does not get passed on to the ListModel or Pagination.

**Comment by bcordis** [comment]
Added the core JS to all List views. Working through the code to update the views with all the new J4 code.

**Comment by bcordis** [comment]
@tomfuller2 Please retest all views and verify if all is fixed.

**Comment by bcordis** [comment]
@tomfuller2

**Comment by bcordis** [comment]
This has been fixed in dev
