### ISSUE TITLE
Server info not save

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#907]
Admin side - change the url for a server and hit save. Joomla reports item saved but info not updated

**Comment by bcordis** [comment]
@tomfuller2 This should be fixed now in development.

**Comment by bcordis** [comment]
Ok ran into another error looking into it more closely, as this could be the problem with our namespace naming.

**Comment by bcordis** [comment]
Fixed both selection and server save. @tomfuller2
