### ISSUE TITLE
Server Addon: An exception is thrown if language is not present

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Proclaim#915]
In my case, german language file is not present. This is not a problem, since ->getLanguage() falls back to english. But in this case (the only case as far as I see), an exception is thrown. 

\admin\src\Model\CWMServerModel.php line 228

Is this really needed? If I comment it out, language works as expected. But to be true: I don't know, why it did work in v9.x with the same code.

**Comment by bcordis** [comment]
Try Branch out and see if it fixes the problem

**Comment by st-anton** [comment]
Sorry for the delay. Unfortunatelly every backend page crashes with `Typed static property CWM\Component\Proclaim\Administrator\Helper\CWMParams::$admin must not be accessed before initialization`

**Comment by bcordis** [comment]
I have fixed the error you were having. Sorry, it did not get fixed sooner. PHP 8 introduces many strict problems, and I have to work through them to get the code working with them.
