### ISSUE TITLE
Add a media file locally link does nothing

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#940]
https://joomla2:8890/fresh/administrator/index.php?option=com_proclaim&view=cwmmediafile&layout=edit&options=c3R1ZHlfaWQ9MSZjcmVhdGVkYXRlPTIwMTAtMDMtMTMgMDA6MTA6MDA&return=aW5kZXgucGhwP29wdGlvbj1jb21fcHJvY2xhaW0mdGFzaz1jd21tZXNzYWdlLmVkaXQmaWQ9MQ

When in a study, select add a media file, then + Add File. Nothing happens. 

Similarly, upload a file also does nothing.

**Comment by bcordis** [comment]
I am looking into using the media file system to work it.

**Comment by bcordis** [comment]
As shown in the documentation, I have been able to add media to the media field type. This may require updating mime types for the files to show up correctly. 

For a MacOS, I could use ( file --mime "/path/to/filename" )  to find the mime type of each file.

https://docs.joomla.org/Special:MyLanguage/Media_form_field_type

**Comment by tomfuller2** [comment]
Adding a new media file. YouTube. Record is added but when clicking on the icon to play the file I get this error:

CWM\Component\Proclaim\Site\Helper\CWMImages::getSeriesThumbnail(): Argument #1 ($image) must be of type string, null given, called in /Users/tomfuller/PhpstormProjects/Proclaim/site/src/View/CWMPopUp/HtmlView.php on line 208

**Comment by tomfuller2** [comment]
I removed the string declaration in getSeriesThumbnail as it caused an unneeded error.
