### ISSUE TITLE
Images do not save for podcast

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#942]
Selected an image from the rotating images folder. When saving got this error:

Save failed with the following error: Data too long for column 'image' at row 1

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PHP Version [e.g. 8.0.0]
 - Joomla Version [e.g. 3.x, 4.x]
 - Proclaim Version [e.g. 10.0.0]

**Additional context**

**Comment by bcordis** [comment]
@tomfuller2 Are we supporting wanting to use external images here or just local ones? Right now, I can save select local images in the media bin.

This may need to be sorted out, as we want to use an image folder, not the media folder.

**Comment by bcordis** [comment]
Found a problem with Joomla 4 using the FileSystem - Local as it needs to add the file location of images. This allows the user to select the right images on the podcast page.

**Comment by bcordis** [comment]
Working on the final fix now

**Comment by bcordis** [comment]
@tomfuller2 Need your replay

**Comment by tomfuller2** [comment]
Need to do more research. Right now I get an error: Save failed with the
following error: Data too long for column 'image' at row 1
Tom Fuller, APR
www.ImaginePublicRelations.com
www.ImagineVisualProductions.com
971-832-9494

**Comment by bcordis** [comment]
@tomfuller2 Looking through the Db looks like a lot of core DB has changed to 255 characters. This may facilitate the fix to the problem

Try changing the DB character limit. and lets see if this fixes the problem.

**Comment by bcordis** [comment]
Fixed in Dev
