### ISSUE TITLE
Podcast file does not write

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#946]
**Describe the bug**
From the Podcasts view, click "Write XML files". Nothing happens.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PHP Version [e.g. 8.0.0]
 - Joomla Version [e.g. 3.x, 4.x]
 - Proclaim Version [e.g. 10.0.0]

**Additional context**

**Comment by bcordis** [comment]
Fixed in dev
