### ISSUE TITLE
Fresh Install Errors 

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#948]
**Describe the bug**
Installing fresh component to https://www.imaginecommunications.xyz/joomla4. Created fresh build from the Phing Component (build errors out in ways I can't fix)

Errors: JInstaller: :Install: File does not exist [ROOT][TMP]/install_64f63c05c0dee/site/helpers
Component Install: Failed to copy site files.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PHP Version [e.g. 8.0.0]
 - Joomla Version [e.g. 3.x, 4.x]
 - Proclaim Version [e.g. 10.0.0]

**Additional context**

**Comment by bcordis** [comment]
Removed Old PHPCPD as there is no replacement. Try using this branch now.

**Comment by tomfuller2** [comment]
Still errors out.

**Comment by tomfuller2** [comment]
I successfully installed the component. Module did not install due to this error:

Copy failed: [ROOT][TMP]/install_6505d98485b32/modules/site/mod_proclaim/services to [ROOT]/modules/mod_proclaim/services
JInstaller: :Install: Failed to copy file [ROOT][TMP]/install_6505d98485b32/modules/site/mod_proclaim/services to [ROOT]/modules/mod_proclaim/services
Module %s: Could not copy files from the source.

**Comment by bcordis** [comment]
Looks like it's thinking /modules/mod_proclaim/services is a file instead of a directory. Need to update the xml.

**Comment by tomfuller2** [comment]
I fixed this. The mod_proclaim.php file had been deleted and the word
"services" put in its place in the xml file. I found the newest version of
the module file, replaced it in the code and changed the xml.

Tom Fuller, APR
Imagine Communications <http://www.ImagineCommunications.xyz>
971-832-9494

**Comment by bcordis** [comment]
Updated branch with your fix.
