### ISSUE TITLE
Import DB Error

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#951]
**Describe the bug**
Try to import an existing db from a file.

Errors:

Joomla\CMS\Filesystem\Folder::files: Path is not a folder. Path: [ROOT]/administrator/components/com_proclaim/install/sql/updates/mysql

Joomla\CMS\Filesystem\Folder::files: Path is not a folder. Path: [ROOT]/administrator/components/com_proclaim/install/updates/

usort(): Argument #1 ($array) must be of type array, string given
JROOT/administrator/components/com_proclaim/src/Model/CWMInstallModel.php:424

Line in question:

$files = str_replace('.sql', '', Folder::files(JPATH_ADMINISTRATOR . $this->filePath, '\.sql$'));
			$php   = str_replace('.php', '', Folder::files(JPATH_ADMINISTRATOR . $this->phpPath, '\.php$'));
424			usort($files, 'version_compare');
			usort($php, 'version_compare');

DB does import, however. Not sure why we fire off the import here.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PHP Version [e.g. 8.0.0]
 - Joomla Version [e.g. 3.x, 4.x]
 - Proclaim Version [e.g. 10.0.0]

**Additional context**

**Comment by bcordis** [comment]
@tomfuller2 We need to decide whether to use PHP for upgrading or remove it.

**Comment by bcordis** [comment]
There are no PHP files to test or need for now, but I will keep the code in.
