### ISSUE TITLE
Audio file does not play on web server but does on localhost

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#952]
**Describe the bug**
go to: https://www.demo.imaginepublicrelations.com/index.php?option=com_proclaim&view=cwmsermons&t=1&Itemid=273
Click on the audio for Pastor Tom's Top Ten Tips for Christians. 
Click Play

You get error: 

![image](https://github.com/Joomla-Bible-Study/Proclaim/assets/1281117/5cb07ec0-3b6c-40e6-bd17-8155a5ec8964)

File does play on Localhost. 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - PHP Version [e.g. 8.0.0]
 - Joomla Version [e.g. 3.x, 4.x]
 - Proclaim Version [e.g. 10.0.0]

**Additional context**

**Comment by bcordis** [comment]
Can you give me details on what server type you used and whether the file is stored locally on the server or using a remote host?

**Comment by tomfuller2** [comment]
The audio file is on a web server. Same address as the Server on the
localhost install as well as on the web-installation.

Tom Fuller, APR
Imagine Communications <http://www.ImagineCommunications.xyz>
971-832-9494

**Comment by tomfuller2** [comment]
I wish I could troubleshoot this but I can't get any errors other than what JW Player shows. This error is:

Failed to play the associated resource because it is not supported by this browser. Equivalent to the HTML5 MEDIA_ERR_SRC_NOT_SUPPORTED mediaError.

The odd thing is that in the same browser, it plays from the localhost.

**Comment by bcordis** [comment]
@tomfuller2 Can you look at this again and send me more info on reproducing the error? thanks

**Comment by tomfuller2** [comment]
I think perhaps the problem is how I'm addressing the remote location. Let's just put this on hold for now. At some point I need to figure out how to address the media files. They are under imagine-communications.site/MediaFiles/ but that ends in a 404.

**Comment by bcordis** [comment]
@tomfuller2 Can we verify this is fixed and no longer a problem.

**Comment by tomfuller2** [comment]
I can't yet test until we resolve the db restore issue. I'm hoping to test on the CWM site.

**Comment by bcordis** [comment]
@tomfuller2 Can you verify this is fixed now?

**Comment by tomfuller2** [comment]
I think this has been fixed
