### ISSUE TITLE
Can't build a package / set up environment

### ISSUE THREAD

**Issue by st-anton** [Joomla-Bible-Study/Proclaim#957]
**Describe the bug**
Trying to build the package with phing. 
Obviuosly the requested libraries/vendor/autoload.php is not present in git.

**To Reproduce**
Setup Phing, and the development branch of the git repo.
Start <path>\php\php ..\phing-latest.phar dev.setup

**Expected behavior**
Set up the development environment or get the install package

**Screenshots**
Buildfile: A:\FeG_Internet_work\xampp_8v1v10\htdocs\phing\Joomla-Bible-Study\build.xml
BUILD FAILED
A:\Internet_work\xampp_8v1v10\htdocs\phing\Joomla-Bible-Study\build.xml:4:79: Provided autoloader file "A:\Internet_work\xampp_8v1v10\htdocs\phing\Joomla-Bible-Study/libraries/vendor/autoload.php" is not a readable file

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - PHP Version [e.g. 8.1.10]
 - Joomla Version [4.2.x]
 - Proclaim Version [-]

**Additional context**
My server hoster starts to put more pressure to me to step over to J4 because of the obsolete J3

**Comment by bcordis** [comment]
Looking into this now.

**Comment by bcordis** [comment]
Here is the alpha build to test with 
[com_proclaim-10.0.0-alpha.20240315.zip](https://github.com/Joomla-Bible-Study/Proclaim/files/14652120/com_proclaim-10.0.0-alpha.20240315.zip)
I am still reworking the build name to reflect it is a package.

**Comment by bcordis** [comment]
@st-anton, Can you try using the late code on Development and test with it?

**Comment by bcordis** [comment]
No response Closing
