### ISSUE TITLE
Migrating from Joomla 3 to 4 leaves wrong admin menu

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#958]
Process: Update Joomla 3 site to 4 without uninstalling Proclaim.
Upload and install new version of Proclaim

Result: Two admin menus for Proclaim. One uses com_biblestudy, the other uses com_proclaim.

Solution? In preflight install, run function to remove entries in menus table with com_biblestudy

**Comment by tomfuller2** [comment]
I attempted a post install function to fix this. I have NOT tested it. https://github.com/Joomla-Bible-Study/Proclaim/commit/d47168b2fa4495cfe3af194fc31e0bf84f76c6fc

**Comment by bcordis** [comment]
Are we planning on cleaning up files post-install and the old version?

**Comment by tomfuller2** [comment]
I've run into an error I can't solve.

Process:
1. Upgrade a J3 site to J4
2. Upload and install new version of Proclaim

Result: 
Old menu items are removed
Component not installed
New menu links installed

Errors:
Unknown column 'com_biblestudy' in 'where clause'
Error installing component

**Comment by bcordis** [comment]
Please reverify this as I believe we fixed this now.

**Comment by tomfuller2** [comment]
This is fixed
