### ISSUE TITLE
Language files missing?

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#959]
After installing the 10 component over the 9.x version, I get these errors:

![image](https://github.com/Joomla-Bible-Study/Proclaim/assets/1281117/afb1299e-7d8a-4ca9-8fc5-e99eddeb8ab4)

The files appear to be there in PhpStorm.

**Comment by bcordis** [comment]
Wonder if the build system did not include it in the folders correctly. Need to look into that

**Comment by bcordis** [comment]
@tomfuller2  This should now be fixed.
