### ISSUE TITLE
JBS/Proclaim not showing up in the landing page

### ISSUE THREAD

**Issue by glgprasad** [Joomla-Bible-Study/Proclaim#960]
our web site [TBOLF.ORG](http://tbolf.org/)
JBS/Proclaim module is not showing in the landing page.
it is working fine in the JBS page.
kindly help brother
Regards
Prasad 
The Bread of Life Fellowship oman.
mobile no 00919177921781
![image](https://github.com/Joomla-Bible-Study/Proclaim/assets/79415321/f267529f-11fa-441f-86e9-6494c5e54d25)
![image](https://github.com/Joomla-Bible-Study/Proclaim/assets/79415321/46ddfefd-c2d3-4443-b3b5-e5975ec1b7da)

**Comment by tomfuller2** [comment]
Turn on Maximum error reporting under System Global Settings, System tab.
Then refresh and report back on any errors. I can see the header of the
module but no studies showing up.

Tom

Tom Fuller, APR
Imagine Communications <http://www.ImagineCommunications.xyz>
971-832-9494

**Comment by bcordis** [comment]
Joomla 3 with Proclaim 9.x must run on PHP 7.4.x.

After downgrading your PHP to 7.4.x, all the data came in on the module. We hope to be able to serve you soon with a new version of Proclaim Joomla software.
