### ISSUE TITLE
CWM Examples pages are broken

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#962]
Going to any of the example pages like https://www.christianwebministries.org/proclaim-home/proclaim-examples/list-of-messages-view.html

Gets this error:

0 Joomla\CMS\Event\Content\ContentPrepareEvent::onSetPage(): Argument #1 ($value) must be of type ?int, string given, called in /home/jbsm_bcc/christianwebministries.org/libraries/src/Event/AbstractEvent.php on line 227

**Comment by bcordis** [comment]
@tomfuller2, can you verify if this is still a problem and, if so, get more details so I can reproduce it and fix it?

**Comment by tomfuller2** [comment]
This is fixed
