### ISSUE TITLE
Strange error upon install to Joomla 4x

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#964]
Error: This command is not supported in the prepared statement protocol yet
Component will not install.

Process:
Joomla 3.x site with Proclaim 9.2
Upgrade to Joomla 4
Install Proclaim 10x.

See if you can duplicate this. I can't find where it is coming from. Seems to be a MySQL error.

**Comment by tomfuller2** [comment]
Also happens in Joomla 5.

Saw this article - but it was of no help.

https://stackoverflow.com/questions/77096553/joomla-4-db-prepared-statement-re-write

**Comment by tomfuller2** [comment]
This article seems to indicate that it might be a database driver issue. They suggest using MySQL (PDO) instead of MySQLi.

https://www.rcatheme.com/docs/joomla-templates-global/how-to-fix-this-command-is-not-supported-in-the-prepared-statement-protocol-yet-error-during-joomla-installation

**Comment by bcordis** [comment]
It sounds like the upgrade of SQL is not happy. We may need to move to a database query and do some PHP if-then statements to move.

**Comment by bcordis** [comment]
We have to support multiple versions of MySQL, and this will make it hard to do it in the Upgrade SQL that we have coded.

**Comment by tomfuller2** [comment]
I added some bind statements to the queries in the install script. Didn't fix errors but maybe I did something wrong?

**Comment by bcordis** [comment]
I added some new Search and Preflight fixes, as some menu and module conventions now need to be tested.

**Comment by tomfuller2** [comment]
This bug was fixed by moving a table fix for the podcast table to the preflight function in the installer script.
