### ISSUE TITLE
Restore function of db throw error

### ISSUE THREAD

**Issue by tomfuller2** [Joomla-Bible-Study/Proclaim#965]
When trying to restore the db from a local file, I get this error:

**You must specify a non-empty path to clean**

Stack:

JROOT/libraries/vendor/joomla/filesystem/src/Path.php:198
--
2 | Joomla\Filesystem\Path::clean() | JROOT/libraries/vendor/joomla/filesystem/src/Folder.php:337
3 | Joomla\Filesystem\Folder::files() | JROOT/administrator/components/com_proclaim/src/Lib/Cwmrestore.php:204
4 | CWM\Component\Proclaim\Administrator\Lib\Cwmrestore->importdb() | JROOT/administrator/components/com_proclaim/src/Controller/CwmadminController.php:620

<br class="Apple-interchange-newline">

**Comment by tomfuller2** [comment]
Look at the very end of this post. One user had a permissioning problem: https://forum.joomla.org/viewtopic.php?t=1005151

It also errors on localhost.

**Comment by bcordis** [comment]
@tomfuller2  I found this error with the exported zip file from Proclaim, as it would not extract even on my computer. See 7b50dfd9bb44b3caa4a182a22bf912823e456e4d
