### ISSUE TITLE
Internal player not playing MP3 media files

### ISSUE THREAD

**Issue by glgprasad** [Joomla-Bible-Study/Proclaim#969]
Internal player not playing MP3 media files

**Comment by tomfuller2** [comment]
Can you give us a url so we can see this happening? We are getting close to releasing a new version that works with Joomla 4/5

**Comment by glgprasad** [comment]
tbolf.org pastor

**Comment by bcordis** [comment]
I just tried a few links, and they all played and are not using the internal player. Can you post a direct link to a page and direct us to the correct link that is not working? Thanks

**Comment by glgprasad** [comment]
Brother,
Earlier i was using , internal player
Which stopped working a couple of days ago.
Then i changed the settings to direct link which was working
Joomla 3.10.
And php 7.4

Regards
Prasad
00919177921781

**Comment by bcordis** [comment]
I'm sorry, but we cannot reproduce the error without the site showing it. Also, is there any reason you use a subfolder for the site? This could fix many rewrite errors and URL-friendly URLs.

**Comment by bcordis** [comment]
Unfortunately, no response is closing for now.
